feat: improved cache handling and implemented redis cache
urbanmedia/passbolt-operator pull request #95
Opened 2023-08-30 15:12 UTC by leonsteinhaeuser

# Description

Improved cache handling for 

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:

- Kubernetes version:
- Kubectl version:
- Node operation system:

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

2023-11-17 10:50 UTC, tom-hauschke approved these changes

2023-11-17 10:56 UTC, tom-hauschke requested changes
typos

2023-11-17 10:56 UTC, tom-hauschke commented on cmd/main.go
> +	ticketRedis := time.NewTicker(5 * time.Minute)
```suggestion
	tickerRedis := time.NewTicker(5 * time.Minute)
```

2023-11-17 10:56 UTC, tom-hauschke commented on cmd/main.go
> +	defer ticketRedis.Stop()
```suggestion
	defer tickerRedis.Stop()
```

2023-11-17 10:56 UTC, tom-hauschke commented on cmd/main.go
> +				case <-ticketRedis.C:
```suggestion
				case <-tickerRedis.C:
```

2023-11-21 10:50 UTC, tom-hauschke requested changes
please fix merge conflicts

2023-11-28 08:25 UTC, closed without merging

2023-11-28 08:25 UTC, leonsteinhaeuser commented
Will be obsolete as soon as we introduce apiVersion: v1alpha3.

See: #118